Guia rápido do módulo numpy
===========================



O módulo `numpy` é utilizado para operações numéricas com vetores e matrizes. É um módulo fundamental para praticamente todos os cientista que utilizam Python na sua prática científica. Este módulo é praticamente sempre importado com o apelido de `np`, como mostra o código abaixo.



In [1]:
import numpy as np

## Criando um array usando listas



O objeto mais fundamental que o `numpy` nos fornece são as matrizes de $n$ dimensões, conhecidas como `ndarray` ou simplesmente `array`.



In [2]:
array_1d = np.array([1, 2, 3])  # array de 1 dimensão

print(array_1d)

lista_de_listas = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

array_2d = np.array(lista_de_listas)  # array de 2 dimensões

print(array_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Criando um array apenas com 0s ou com 1s



In [3]:
array1 = np.zeros(10)
array2 = np.zeros((3, 4))

array3 = np.ones(5)
array4 = np.ones((2, 3))

print(array1)
print(array2)
print(array3)
print(array4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


## Criando um array com uma sequência numérica linear com passo bem definido



In [4]:
array1 = np.arange(10)  # com apenas um argumento, ele inicia sempre do zero
array2 = np.arange(10, 20)
array3 = np.arange(0, 110, 10)
array4 = np.arange(0, 1, 0.1)  # o intervalo não precisa ser inteiro!

print(array1)
print(array2)
print(array3)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[  0  10  20  30  40  50  60  70  80  90 100]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## Criando um array com uma sequência numérica linear com número de itens bem definido



In [5]:
array1 = np.linspace(0, 1, 101)  # array com 101 valores entre 0 e 1
array2 = np.linspace(0, 10, 5)  # array com 5 valores entre 0 e 10
array3 = np.linspace(0, 10)  # sem o último argumento ele gera 50 números

print(array1)
print(array2)
print(array3)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102

## Criando um array com uma sequência numérica espaçada logaritmicamente



In [6]:
array1 = np.logspace(0, 10, 30)  # array com 30 valores entre 10**0 e 10**10
array2 = np.logspace(-5, 5, 15)  # array com 15 valores entre 10**-5 e 10**5
array3 = np.logspace(0, 2)  # sem o último argumento ele gera 50 números

print(array1)
print(array2)
print(array3)

[1.00000000e+00 2.21221629e+00 4.89390092e+00 1.08263673e+01
 2.39502662e+01 5.29831691e+01 1.17210230e+02 2.59294380e+02
 5.73615251e+02 1.26896100e+03 2.80721620e+03 6.21016942e+03
 1.37382380e+04 3.03919538e+04 6.72335754e+04 1.48735211e+05
 3.29034456e+05 7.27895384e+05 1.61026203e+06 3.56224789e+06
 7.88046282e+06 1.74332882e+07 3.85662042e+07 8.53167852e+07
 1.88739182e+08 4.17531894e+08 9.23670857e+08 2.04335972e+09
 4.52035366e+09 1.00000000e+10]
[1.00000000e-05 5.17947468e-05 2.68269580e-04 1.38949549e-03
 7.19685673e-03 3.72759372e-02 1.93069773e-01 1.00000000e+00
 5.17947468e+00 2.68269580e+01 1.38949549e+02 7.19685673e+02
 3.72759372e+03 1.93069773e+04 1.00000000e+05]
[  1.           1.09854114   1.20679264   1.32571137   1.45634848
   1.59985872   1.75751062   1.93069773   2.12095089   2.32995181
   2.55954792   2.8117687    3.0888436    3.39322177   3.72759372
   4.09491506   4.49843267   4.94171336   5.42867544   5.96362332
   6.55128557   7.19685673   7.90604321   8.685

## Criando um array populado com números aleatórios



In [7]:
array_1d = np.random.random(10)
array_2d_3x3 = np.random.random((3, 3))
array_2d_5x4 = np.random.random((5, 4))

print(array_1d)
print(array_2d_3x3)
print(array_2d_5x4)

[0.85684571 0.91422021 0.80032767 0.01173845 0.14472201 0.75961915
 0.99289811 0.97219852 0.58311706 0.48055717]
[[0.10950477 0.18541475 0.06401112]
 [0.06550411 0.01813945 0.00090168]
 [0.57999338 0.79190135 0.31417747]]
[[0.24108284 0.64075072 0.52815057 0.58304509]
 [0.43133985 0.52586936 0.68051789 0.28989814]
 [0.72022798 0.06583255 0.82290778 0.5885641 ]
 [0.12024669 0.85724615 0.77994029 0.56304874]
 [0.68428443 0.8609106  0.03549625 0.54423713]]


## Aplicando funções em arrays



Quando aplicamos funções em arrays nosso interesse geralmente é que a função seja aplicada para cada elemento do array. O próprio `numpy` já tem diversas funções prontas que atuam desta maneira.



In [8]:
array = np.array([1, 2, 3])

print(np.log(array))    # logaritmo natural (base e)
print(np.log10(array))  # logaritmo base 10
print(np.exp(array))    # exponencial
print(np.cos(array))    # cosseno
print(np.sin(array))    # seno
print(np.tan(array))    # tangente
print(np.sqrt(array))   # raiz quadrada

[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[ 2.71828183  7.3890561  20.08553692]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 1.55740772 -2.18503986 -0.14254654]
[1.         1.41421356 1.73205081]


## Usando operadores de Python com arrays



Os operadores de Python costumam operar em termos de elementos nos arrays.



In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


## Funções agregadoras (sem direcionalidade)



Soma dos elementos, mínimo, máximo, média e desvio padrão são operações chamadas agregadoras que são muito utilizadas. Arrays de `numpy` nos permitem computar esses valores de maneira muito fácil! Veja o exemplo abaixo.



In [10]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.sum(array))           # soma
print(np.min(array))           # mínimo
print(np.max(array))           # máximo
print(np.mean(array))          # média
print(np.std(array, ddof=0))   # desvio padrão (zero grau de liberdade)
print(np.std(array, ddof=1))   # desvio padrão (um grau de liberdade)

45
1
9
5.0
2.581988897471611
2.7386127875258306


In [11]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

print(np.sum(array))           # soma
print(np.min(array))           # mínimo
print(np.max(array))           # máximo
print(np.mean(array))          # média
print(np.std(array, ddof=0))   # desvio padrão (zero grau de liberdade)
print(np.std(array, ddof=1))   # desvio padrão (um grau de liberdade)

45
1
9
5.0
2.581988897471611
2.7386127875258306


## Funções agregadoras (com direcionalidade)



Quando queremos realizar uma operação agregadora em uma certa direção do nosso array, nós precisamos usar o argumento `axis`.

Se quisermos realizar uma operação &ldquo;ao longo das linhas&rdquo; usamos `axis=0`. Lembre-se que uma matriz $n \times m$ é definida como uma matriz de $n$ linhas e $m$ colunas. O número de linhas é declarado primeiro, por isso usamos o valor zero no argumento `axis` (pois linhas são a primeira dimensão e o Python começa a contar pelo zero).



In [12]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

print(np.sum(array, axis=0))           # soma
print(np.min(array, axis=0))           # mínimo
print(np.max(array, axis=0))           # máximo
print(np.mean(array, axis=0))          # média
print(np.std(array, axis=0, ddof=0))   # desvio padrão (zero grau de liberdade)
print(np.std(array, axis=0, ddof=1))   # desvio padrão (um grau de liberdade)

[12 15 18]
[1 2 3]
[7 8 9]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]
[3. 3. 3.]


Se quisermos realizar uma operação &ldquo;ao longo das colunas&rdquo; usamos `axis=1`.



In [13]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

print(np.sum(array, axis=1))           # soma
print(np.min(array, axis=1))           # mínimo
print(np.max(array, axis=1))           # máximo
print(np.mean(array, axis=1))          # média
print(np.std(array, axis=1, ddof=0))   # desvio padrão (zero grau de liberdade)
print(np.std(array, axis=1, ddof=1))   # desvio padrão (um grau de liberdade)

[ 6 15 24]
[1 4 7]
[3 6 9]
[2. 5. 8.]
[0.81649658 0.81649658 0.81649658]
[1. 1. 1.]


## Indexando arrays



Sintaxe similar a de listas:



In [14]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

linha_0 = array[0]
linha_1 = array[1]
linha_2 = array[2]

linhas_0_e_1 = array[:2]
linhas_1_e_2 = array[1:]

linha_0_coluna_0 = array[0][0]
linha_1_coluna_2 = array[1][2]

print(linha_0)
print(linha_1)
print(linha_2)
print()
print(linhas_0_e_1)
print(linhas_1_e_2)
print()
print(linha_0_coluna_0)
print(linha_1_coluna_2)

[1 2 3]
[4 5 6]
[7 8 9]

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]

1
6


Sintaxe própria do `numpy` (que não funciona para listas!):



In [15]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

linha_0_coluna_0 = array[0, 0]
linha_1_coluna_2 = array[1, 2]

# O `:` indica `todos os elementos desta posição`
coluna_0 = array[:, 0]
coluna_1 = array[:, 1]
coluna_2 = array[:, 2]

print(linha_0_coluna_0)
print(linha_1_coluna_2)
print()
print(coluna_0)
print(coluna_1)
print(coluna_2)

1
6

[1 4 7]
[2 5 8]
[3 6 9]


## Atributos e peculiaridades de arrays



Atributos para extrairmos informações dos arrays:



In [16]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

print(array.shape)  # formato do array
print(array.ndim)   # número de dimensões
print(array.size)   # quantidade de valores que tem no array
print(array.dtype)  # tipo dos dados armazenados no array

(3, 3)
2
9
int64


Diferentemente de listas, arrays não têm os métodos `append`, `remove`, `pop` e `extend`. Uma vez que o array foi criado, seu tamanho não pode ser alterado. Mas podemos alterar seu formato! Para isso usamos o método `reshape`.



In [17]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

array_2 = array.reshape((1, 9))  # 1 linha e 9 colunas
array_3 = array.reshape((9, 1))  # 9 linhas e 1 coluna

print(array)
print(array_2)
print(array_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Veja que as operações do `numpy` nunca geram uma *cópia* do seu array, apenas uma *visão* dele. Sabemos que visões de objetos podem nos levar a erros quando alteramos os valores do objeto! Vamos ver um exemplo:



In [18]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

array_2 = array.reshape((1, 9))  # 1 linha e 9 colunas
array_3 = array.reshape((9, 1))  # 9 linhas e 1 coluna

array_2[0, 0] = 10  # alteramos o valor da linha 0 e da coluna 0 apenas do array_2

# veja que todos os arrays foram alterados!!!
print(array)
print(array_2)
print(array_3)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[10  2  3  4  5  6  7  8  9]]
[[10]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]]


Então sempre que precisar, crie uma cópia do seu array com o método `copy`.



In [19]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

array_2 = array.reshape((1, 9)).copy()  # cópia!!
array_3 = array.reshape((9, 1))

array_2[0, 0] = 10  # alteramos o valor da linha 0 e da coluna 0 apenas do array_2

print(array)
print(array_2) # apenas esse foi modificado pois ele é uma cópia!
print(array_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3  4  5  6  7  8  9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## Algumas operações de álgebra linear



Multiplicação matricial entre dois arrays pode ser feita com o operador `@` (também conhecido com operador de multiplicação matricial).



In [20]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

multiplicacao = array @ array

print(multiplicacao)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


A matriz transposta de um array pode ser obtida com o atributo `T`.



In [21]:
array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

transposta = array.T

print(array)
print()
print(transposta)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


O determinante de uma matriz pode ser calculado com a função `linalg.det` e a inversa de uma matriz pode ser calculada com a função `linalg.inv`.



In [22]:
array = np.array(
    [
        [5, 2, 3],
        [4, 5, 6],
        [7, 8, 5],
    ]
)

determinante = np.linalg.det(array)
inversa = np.linalg.inv(array)

print(determinante)
print()
print(inversa)

-79.99999999999997

[[ 0.2875 -0.175   0.0375]
 [-0.275  -0.05    0.225 ]
 [ 0.0375  0.325  -0.2125]]
